# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - hogarquest-api-uts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: hogarquestacr.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_F96306F2BC3D4DFBAC1124747BB98CF8 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_B152E9CEA4AF4FE3A6E170A3312CA57B }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: hogarquestacr.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_F96306F2BC3D4DFBAC1124747BB98CF8 }}/hogarquest-server:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7A18266D4C30424AAB40CE5469DC06D3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BCA3925C610346B09DFE398541BD4856 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0127F568907B486B85C06C7CBD566CC1 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hogarquest-api-uts'
          slot-name: 'Production'
          images: 'hogarquestacr.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_F96306F2BC3D4DFBAC1124747BB98CF8 }}/hogarquest-server:${{ github.sha }}'
          